version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 10
    directory: "/sample-plugin"
    schedule:
      interval: "daily"
    target-branch: "staging"
  - package-ecosystem: "maven"
    open-pull-requests-limit: 25
    directory: "/bom-weekly"
    schedule:
      interval: "daily"
    target-branch: "staging"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "staging"
